on:

name: Build Windows EXE

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 0.1, 0.2)'
        required: true
        default: '0.1'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          # Use the icon at extension/images/alisa.ico for the EXE file
          if [ -f extension/images/alisa.ico ]; then
            pyinstaller --onefile --name alisa --icon extension/images/alisa.ico main.py
          else
            pyinstaller --onefile --name alisa main.py
          fi

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: alisa-windows-exe
          path: dist/alisa.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          body: |
            Automated release for version v${{ github.event.inputs.version }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          files: dist/alisa.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
